kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage1
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume1
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: jenkins-pv-claim1
    namespace: jenkins
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - aks-agentpool-31443139-vmss000000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim1
  namespace: jenkins
spec:
  storageClassName: local-storage1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
